export const START_TRANSACTIONS_DATA = 'START_TRANSACTIONS_DATA';
export const RECEIVE_TRANSACTIONS_DATA = 'RECEIVE_TRANSACTIONS_DATA';
export const FAIL_TRANSACTIONS_DATA = 'FAIL_TRANSACTIONS_DATA';

export const START_CREATE_TRANSACTION = 'START_CREATE_TRANSACTION';
export const SUCCESSFUL_CREATE_TRANSACTION = 'SUCCESSFUL_CREATE_TRANSACTION';
export const FAIL_CREATE_TRANSACTION = 'FAIL_CREATE_TRANSACTION';
