export const START_FETCH_FILTERED_USER_LIST = 'START_FETCH_FILTERED_USER_LIST';
export const RECEIVE_FILTERED_USER_LIST = 'RECEIVE_FILTERED_USER_LIST';
export const FAIL_FETCH_FILTERED_USER_LIST = 'FAIL_FETCH_FILTERED_USER_LIST';
